# Generated by Django 3.2.5 on 2022-07-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorturl', models.CharField(max_length=100)),
                ('longurl', models.CharField(max_length=300)),
            ],
        ),
    ]
