# Generated by Django 3.2.5 on 2022-07-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0002_rename_farmer_urltable'),
    ]

    operations = [
        migrations.AddField(
            model_name='urltable',
            name='slno',
            field=models.IntegerField(null=True),
        ),
    ]
